### ISSUE TITLE
`tiles` directory missing

### ISSUE THREAD

**Issue by timonegk** [Schmitzi/mahjong-tex#1]
Hi, I just stumbled upon this cool project and wanted to give it a try. However, in the repository, the `tiles` folder seems to be missing, probably because `.pdf` files are excluded in the `gitignore`. Could you add the missing folder?

**Comment by Schmytzi** [comment]
Hi,

Thank you for pointing that out! I have added the files.
They should be visible now.

**Comment by timonegk** [comment]
Great, thank you!
